### ISSUE TITLE
script availability

### ISSUE THREAD

**Issue by snapo** [arcee-ai/PruneMe#11]
Do you maybe have the script available with which you created this graph:

![image](https://github.com/user-attachments/assets/97f832c5-e7fb-428b-ad98-b280d763d6b8)

Would love to do create that graph for a small 1.2B model of mine that i am working on. (this would allow me to lock specific layers, so that all layers provide the same ammount of information)

**Comment by shamanez** [comment]
I just converted the output CSV to a graph :D
