### ISSUE TITLE
Another interesting paper related to this idea

### ISSUE THREAD

**Issue by jukofyork** [arcee-ai/PruneMe#3]
[Not all Layers of LLMs are Necessary during Inference (v2)](https://arxiv.org/abs/2403.02181v2)

**Comment by shamanez** [comment]
Interesting!

**Comment by jukofyork** [comment]
I've also read another paper along these lines too (but can't find it atm) that suggests the layers marked by the yellow areas at the bottom:

![2](https://github.com/arcee-ai/PruneMe/assets/69222624/0ac9f02e-6765-46d9-9779-c784ac86a985)

are just doing some kind of "averaging", and IIRC the paper suggests replacing these penultimate layers with some other much cheaper operation (IIRC, it was a training time modification rather than post-training though).

**Comment by jukofyork** [comment]
[ShortGPT: Layers in Large Language Models are More Redundant Than You Expect](https://arxiv.org/abs/2403.03853v2)

Can't find the paper about  "averaging" though.
