### ISSUE TITLE
Results from LLaMA-3-70B

### ISSUE THREAD

**Issue by catid** [arcee-ai/PruneMe#4]
To save you $$ on runpods, here's what I found for this model:

```
python ./compute_block_similarity/layer_similarity.py \
    --model_path "Meta-Llama-3-70B-Instruct" \
    --dataset "arcee-ai/sec-data-mini" \
    --dataset_column "text" \
    --batch_size 1 \
    --max_length 8192 \
    --layers_to_skip 8 \
    --dataset_size 4000 \
    --dataset_subset "train" 
```

For `layers_to_skip = 8`: 56-64 are the closest.
For `layers_to_skip = 4`: 60-64 are the closest.
For `layers_to_skip = 2`: 66-68 are the closest.

```
INFO:root:Layer 56 to 64 has the minimum average distance of 0.1385004425048828
INFO:root:Layer 60 to 64 has the minimum average distance of 0.09657025909423828.
INFO:root:Layer 66 to 68 has the minimum average distance of 0.06669809722900391
```

**Comment by yeliang2258** [comment]
INFO:root:Layer 56 to 64 has the minimum average distance of 0.1385004425048828

Hello, when we receive the above Info, should the layers we need to prune be indexed at 66, 67 or at 67, 68?
