### ISSUE TITLE
code to reproduce all experiments

### ISSUE THREAD

**Issue by pkulium** [arcee-ai/PruneMe#6]
Great work! I am wondering if you can provide code to reproduce all experiments in the paper?

**Comment by shamanez** [comment]
This is an unofficial repo of the paper :). 

But the experiment setup is pretty straightforward if you want to do it. 



1. This repo - Find which layers/blocks to prune 
2. Mergekit - Prune those layers and push the model to the HF hub.
3. Tune the model fully or with LORA
