### ISSUE TITLE
Cuda OOM

### ISSUE THREAD

**Issue by emillykkejensen** [arcee-ai/PruneMe#7]
Don't ask me why, but out of the blue I started getting Cuda Out of Memory, everytime I had run a single batch??

The solution was quite simply, to add `del outputs` ones `get_last_non_padded_tokens` was finished.

So maybe add that?

https://github.com/arcee-ai/PruneMe/blob/faee6c9dfb70841e8355908ecded2b25298cffc0/compute_block_similarity/layer_similarity.py#L62

**Comment by shamanez** [comment]
Yeah makes sense. We do not need them after we compute the last_non_padded_tokens.  Could your  please submit a PR?
