### ISSUE TITLE
How to merge the odd number layers of a model?

### ISSUE THREAD

**Issue by eta1232002** [arcee-ai/PruneMe#8]
How to merge the odd number layers of the same model using slices and layer_range? .. Can I do the following code:

slices:
  - sources:
      - model: mistralai/Mistral-7B-Instruct-v0.2
        layer_range: [1, 3, 5, 7, 9, 11, ... ]

            
merge_method: passthrough
dtype: bfloat16

**Comment by shamanez** [comment]
I think you can look into our mergekit repo. Especially the slice merging method.
